name: Master build
env:
  TAG: "latest"
  DOCKER_ORG: enmasse
  KUBERNETES_NAMESPACE: "enmasse-infra"
  REGISTRY_USER: "enmasse+ci"

on:
  schedule:
    - cron:  '0 */2 * * *'

jobs:
  smoke:
    strategy:
      matrix:
        refs: [refs/heads/master]
    name: Smoke tests and Release

    env:
      DOCKER_REGISTRY: "quay.io"
      TAG: "latest"
      RELEASE: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set version
        id: version
        run: |
          echo "::set-env name=VERSION::$(grep "release.version" pom.properties| cut -d'=' -f2)"
          echo "::set-output name=VERSION::$(grep "release.version" pom.properties| cut -d'=' -f2)"

      - name: Install dependencies
        run: ./.github/scripts/install_dep.sh

      - name: setup-docker
        run: ./.github/scripts/setup_docker.sh

      - name: Minikube setup with registry
        uses: EnMasseProject/minikube-setup@V1.0.0
        with:
          k8s-version: 1.15.0

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Setup OLM
        run: ./.github/scripts/setup-olm.sh

      - name: Build
        id: build
        run: |
          export REGISTRY_PASS=${{ secrets.REGISTRY_PASS }}
          ./.github/scripts/build.sh

      - name: Smoke tests
        run: ./.github/scripts/smoke_test.sh

      - name: OLM tests
        run: ./.github/scripts/olm_test.sh

      - name: Collect logs
        if: failure()
        run: ./.github/scripts/collectLogs.sh

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: smoke-test-logs
          path: test-logs.zip

