name: Smoke tests
env:
  DOCKER_REGISTRY: "localhost:5000"
  TAG: "latest"
  DOCKER_ORG: enmasse
  KUBERNETES_NAMESPACE: "enmasse-infra"
  SYSTEMTEST_PROFILE: smoke
  SMOKE: true

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master      
    
    - name: setup-docker
      run: ./.github/scripts/setup_docker.sh
    
    - name: Minikube setup with registry
      uses: EnMasseProject/minikube-setup@V1.0.0
      with:
        k8s-version: 1.15.0
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.2

    - name: Setup Ruby environment with ruby-build
      uses: clupprich/ruby-build-action@v1.0.0
  
    - name: Install dependencies
      run: ./.github/scripts/install_dep.sh
    
    - name: Setup OLM
      run: ./.travis/setup-olm.sh

    - name: Build
      run: ./.github/scripts/build.sh

    - name: Smoke tests
      run: ./.github/scripts/test.sh

    - name: Collect logs
      if: failure()
      run: ./.github/scripts/collectLogs.sh

    - name: Upload artifacts
      if: failure()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: test-logs
        path: artifacts
